server:
  port: 8115


spring:
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.244.237:3306/chengfeng?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        login-username: admin
        login-password: admin
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.beautifulsoup.chengfeng.pojo
logging:
  level:
    org.springframework.web: DEBUG
